server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always